NPCPortal/Areas/Admin/Controllers/LogsController.cs
using NPCPortal.Models;
using NPCPortal.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NPCPortal.Areas.Admin.Controllers
{
    public class LogsController : NPCPortal.Controllers.BaseController
	{
		[NPCAuthorize(PermissionTypes.ViewLogs)]
        public ActionResult Index(string query = null)
        {
			var logs = db.LogMessages.Where(m => true);
			if (!String.IsNullOrEmpty(query))
			{
				foreach (string s in query.Split(new char[] { }))
				{
					logs = logs.Where(m => m.Message.Contains(s));
				}
			}

			if (!String.IsNullOrEmpty(Request["filter"]))
			{
				var filters = Request["filter"].Split(',').Select(f => (LogLevel)Enum.Parse(typeof(LogLevel), f));

				logs = logs.Where(l => filters.Any(f => f == l.Level));
			}
			
			Pager pager = new Pager(logs.Count());
			ViewBag.Pager = pager;

			logs = logs.OrderByDescending(m => m.Date).Skip((pager.CurrentPage - 1) * pager.RecordsPerPage).Take(pager.RecordsPerPage);

			return View(logs);
        }

		[NPCAuthorize(PermissionTypes.ViewLogs)]
		public ActionResult Clear()
		{
			foreach (var log in db.LogMessages.ToArray())
			{
				db.LogMessages.Remove(log);
			}
			db.SaveChanges();

			return RedirectToAction("Index");
		}
	}
}

NPCPortal/Areas/Admin/Views/Logs/Index.cshtml
@model IEnumerable<NPCPortal.Models.LogMessage>

@{
	ViewBag.Title = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
	var pager = ViewBag.Pager as Pager;
}

<div class="page-header">
	<h2 class="pull-left">Log Messages</h2>
	<a href="@Url.Action("Clear")" class="btn btn-default pull-right" style="margin-top: 15px">Clear Logs</a>
	<div class="clearfix"></div>
</div>
@using (Html.BeginForm("Index", "Logs", FormMethod.Get, new { @class = "form-inline" }))
{
	<div class="form-group">
		<input type="search" class="form-control" name="query" placeholder="Search..." value="@Request["query"]">
	</div>
	<div class="form-group">
	</div>
	<div class="form-group">
		@foreach(var severity in Enum.GetValues(typeof(LogLevel)).OfType<LogLevel>().OrderByDescending(l => l))
		{
			<label class="checkbox-inline">
				@if (Request["filter"] != null && Request["filter"].Contains(severity.ToString()))
				{
					<input type="checkbox" name="filter" value="@severity" checked />
				}
				else
				{
					<input type="checkbox" name="filter" value="@severity"/>
				}
				@severity
			</label>
		}
	</div>	
	<div class="form-group">
	</div>
	<button type="submit" class="btn btn-default">Filter</button>
	if(!String.IsNullOrEmpty(Request["filter"]) && !String.IsNullOrEmpty(Request["query"]))
	{ 
		<a href="/admin/logs" class="btn btn-default">Clear</a>
	}
}


@foreach (var item in Model)
{
	<hr />
	<div>
		<h5>
			@DisplayForLogLevel(item.Level) @item.Date.ToTimeZoneString()
		</h5>
		<pre>@Html.DisplayFor(modelItem => item.Message)</pre>
	</div>
}

@Html.Partial("_Pager", pager)

@helper DisplayForLogLevel(LogLevel level)
{
	switch(level)
	{
		case LogLevel.Debug:
			<span class="label label-default">@StringHelpers.GetEnumDescription(level)</span>
			break;
		case LogLevel.Info:
			<span class="label label-info">@StringHelpers.GetEnumDescription(level)</span>
			break;
		case LogLevel.Warning:
			<span class="label label-warning">@StringHelpers.GetEnumDescription(level)</span>
			break;
		case LogLevel.Error:
			<span class="label label-danger">@StringHelpers.GetEnumDescription(level)</span>
			break;
		default:
			<span class="label label-default">@StringHelpers.GetEnumDescription(level)</span>
			break;
	}
}